export const DISCIPLINE_LIST_REQUEST = 'DISCIPLINE_LIST_REQUEST'
export const DISCIPLINE_LIST_SUCCESS = 'DISCIPLINE_LIST_SUCCESS'
export const DISCIPLINE_LIST_FAIL = 'DISCIPLINE_LIST_FAIL'


export const DISCIPLINE_DETAILS_REQUEST = 'DISCIPLINE_DETAILS_REQUEST'
export const DISCIPLINE_DETAILS_SUCCESS = 'DISCIPLINE_DETAILS_SUCCESS'
export const DISCIPLINE_DETAILS_FAIL = 'DISCIPLINE_DETAILS_FAIL'